@BaseURL = http://127.0.0.1:3000


### 使用 filter 过滤错误
GET {{BaseURL}}

### 测试连接
GET {{BaseURL}}/test
    ?id=23423
Token: 123456

### 参数类型验证
GET {{BaseURL}}/ppp
    ?name=1

### 发送短信（对象类型验证）
POST {{BaseURL}}/sms
Content-Type: application/json

{
    "phone": "1234567890",
    "code": "acbn"
}

### 获取消息
GET {{BaseURL}}/notify



### 过去文件

GET {{BaseURL}}/file/1689670686788-633262.png
Custom: 123